### ISSUE TITLE
After switching between tabs the viewer just shows a blank white image.

### ISSUE THREAD

**Issue by pseudo-usama** [BenWeisz/TinyViewer#1]

**Comment by BenWeisz** [comment]
Hey, sorry for the late response, Im aware of the issues but have been too busy with the work + school. Unfortunately there are some problems with it but Ill try to solve them soon. I should have more time now. It should work with relatively small files though, something like 100 x 100. I have to implement huffman compression to handle larger images

**Comment by BenWeisz** [comment]
@pseudo-usama could you please send me one of your TGA / PPM file?

**Comment by pseudo-usama** [comment]
Here is a example [image](https://github.com/BenWeisz/TinyViewer/files/6290183/test.txt).
It actually a `PPM` file. But due to Github upload file extension reasons I've changed it to txt.

**Comment by pseudo-usama** [comment]
> I have to implement huffman compression to handle larger images

You don't have to implement huffman compression from scratch. I mean search for it there might be some libraries out there.
Check these:
https://github.com/kelreel/huffman-javascript
https://gist.github.com/1995eaton/86f10f4d0247b4e4e65e

**Comment by BenWeisz** [comment]
I'll take a look at those libraries but Im really looking for something that can convert everything including the tree to a byte array. 
Also just a heads up it looks like your file format is a bit off because I think the spec for P3 is that each line can have only 70 characters.

https://en.wikipedia.org/wiki/Netpbm#PPM_example

**Comment by BenWeisz** [comment]
@pseudo-usama 
Fixed with [this](https://github.com/BenWeisz/TinyViewer/commit/148c3b24472c34d9e39d0d5561940559cc8feed0) commit. Please update of reinstall the extension.
